version: "3.9"
services:
  rstudio:
    image: "$GGPLOT2_WORKSHOP_IMAGE" 
    ports:
      - "8787:8787"
    volumes:
      - type: "bind"
        source: "$GGPLOT2_WORKING_WORKING_DIR"
        target: "/home/rstudio"
      - type: "bind"
        source: "$RSTUDIO_CONFIG_PATH"
        target: "/home/rstudio/.config/rstudio"